{% set name = "symfc" %}
{% set version = "1.5.4" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/symfc-{{ version }}.tar.gz
  sha256: 7877ba2e7bfaf54d1da0184b45714e873f5e61297270478d49c28c6b0ae063a1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy >=1.11.3
    - spglib

test:
  imports:
    - symfc
  source_files:
    - tests
  commands:
    - pip check
    - pytest
  requires:
    - python {{ python_min }}
    - pip
    - pytest

about:
  home: https://github.com/symfc/symfc
  description: |
    Symfc is a software designed to compute force constants from
    displacement-force datasets in the supercell approach, ensuring they meet
    the required symmetry constraints.
  summary: This is the symfc module.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - atztogo
